services:
  discord-bot:
    image: python:3.14-slim
    container_name: fumi-dc
    restart: unless-stopped

    working_dir: /app
    volumes:
      - .:/app

    env_file:
      - .env

    command: >
      sh -c "
      python -m venv /opt/venv &&
      . /opt/venv/bin/activate &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python main.py
      "

